const searchedData = [
	{
		id: 1,
		name: 'AMG Charging Station',
		location: 'Sector 7, Karnal NH-1, GT-Road, Haryana, 137001',
		type: 'fast',
		isAvailable: true,
		timeSlot: '8:00 - 9:00 AM',
		price: '999',
		rating: 4,
	},
	{
		id: 2,
		name: 'AMG Charging Station',
		location: 'Sector 7, Karnal NH-1, GT-Road, Haryana, 137001',
		type: 'fast',
		isAvailable: true,
		timeSlot: '8:00 - 9:00 AM',
		price: '999',
		rating: 4,
	},

	{
		id: 3,
		name: 'AMG Charging Station',
		location: 'Sector 7, Karnal NH-1, GT-Road, Haryana, 137001',
		type: 'fast',
		isAvailable: true,
		timeSlot: '8:00 - 9:00 AM',
		price: '999',
		rating: 4,
	},
	{
		id: 4,
		name: 'AMG Charging Station',
		location: 'Sector 7, Karnal NH-1, GT-Road, Haryana, 137001',
		type: 'fast',
		isAvailable: true,
		timeSlot: '8:00 - 9:00 AM',
		price: '999',
		rating: 4,
	},
	{
		id: 5,
		name: 'AMG Charging Station',
		location: 'Sector 7, Karnal NH-1, GT-Road, Haryana, 137001',
		type: 'fast',
		isAvailable: true,
		timeSlot: '8:00 - 9:00 AM',
		price: '999',
		rating: 4,
	},
]

export default searchedData;